
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alumno.gui;

import fecha.MiCalendario;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import persona.Alumno;
import persona.PersonaException;
/**
 *
 * @author Intel
 */
public class AlumnoDialog extends javax.swing.JDialog {
//Crea un tipo de alumno Data Access Object, tiene la misma estructura pero con particularidades para mostrar por pantalla
//se usa este objeto en toda esta parte del proyecyo
    private Alumno aluDTO;
    //se usa para saber si va a guardar
    private boolean isSave;
    
    /**
     * Creates new form AlumnoDialog
     */
    //constructor con 2 parametros, recibe unpadre y un boolean
    public AlumnoDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //pone título y se centra
        setTitle("Datos Alumno");
        setLocationRelativeTo(null);
        //deshabilita estado, pero el profesor pidio que se pueda editar
        //estadoTextField.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        numDocTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        apynTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fecNacDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        sexoComboBox = new javax.swing.JComboBox<>();
        saveButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        promTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fecIngDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        cantMatAprobTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        estadoTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("DNI:");

        jLabel2.setText("Apellido y Nombre:");

        apynTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apynTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Fecha de Nacimiento:");

        jLabel4.setText("Sexo:");

        sexoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));

        saveButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        saveButton.setText("GUARDAR.");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Promedio");

        jLabel6.setText("Materias aprobadas:");

        jLabel7.setText("Fecha de Ingreso:");

        jLabel8.setText("Estado:");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("DATOS PERSONALES.");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 255));
        jLabel10.setText("DATOS INSTITUCIONALES.");

        estadoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoTextFieldActionPerformed(evt);
            }
        });

        jLabel11.setText("A=Alta M=Modificado B=Baja");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numDocTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(70, 70, 70))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(apynTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addComponent(jLabel10))
                                    .addComponent(jLabel7)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(promTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(36, 36, 36))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(saveButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fecIngDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(fecNacDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(98, 98, 98)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(sexoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(220, 220, 220)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(cantMatAprobTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(estadoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numDocTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apynTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sexoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fecNacDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fecIngDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cantMatAprobTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(promTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(estadoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(saveButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void apynTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apynTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apynTextFieldActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            //Si el documeno es null o vacio da un mensaje y vuelve
            if(numDocTextField.getText() == null || "".equals(numDocTextField.getText()))
                {
                    JOptionPane.showMessageDialog(this, "El DNI no puede estar vacio.","Error de DNI",JOptionPane.ERROR_MESSAGE);
                    return;
                }
        //llama al metodo form2Alu que carga alu con los textField
            form2Alu();
        } catch (PersonaException ex) {
            Logger.getLogger(AlumnoDialog.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error: " + ex,"Error en la Creacion",JOptionPane.ERROR_MESSAGE);
            return;
        }     
//marca en true la variable isSave y le quita visibilidad al boton guardar
        isSave = true;
        setVisible(false);        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void estadoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlumnoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlumnoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlumnoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlumnoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AlumnoDialog dialog = new AlumnoDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

//crea el metodo mostrar que se usa en los botones agregar, modificar y consultar
    Alumno mostrar(Alumno alu, boolean isUpdate) throws PersonaException {
        //si alumno nes null, lo crea
        if (alu==null) {
        //si es null lo crea para avitar nu nullpointer exception
            alu = new Alumno();
        }
        else {
        //llama al metodo que setea los textField tomandolos de alu con los get
            alu2Form(alu);
        //llama al metodo que habilita o deshabilita fecNacDateChooser dependiendo de la acción
            habilitarDeshabilitar(isUpdate);
        }
        //carga en aluDto al alu
        aluDTO=alu;
        // Se Supende la ejecución para mostrar los datos. Se libera cuando se cierra el diálogo (setVisible(false))
        setVisible(true);
        
        // se cerró el diálogo
        if (!isSave) {
            return null;
        }
        //llama al metodo que carga a alu con los textfield
        form2Alu();
        return this.aluDTO;
    }
//metodo que carga al Alumno aluDTO con los textfield
    private void form2Alu() throws NumberFormatException, PersonaException {
        aluDTO.setDni(Integer.valueOf(numDocTextField.getText()));
        aluDTO.setApyNom(apynTextField.getText());
        //para tomar setFechaNac crea un MiCalendario con el metodo creado.
        aluDTO.setFechaNac(new MiCalendario(fecNacDateChooser.getCalendar()));
        //el string seleccionado (f - m) del combobox lo pasa a caracter
        aluDTO.setSexo(sexoComboBox.getSelectedItem().toString().toUpperCase().charAt(0));
        aluDTO.setCantMatAprob(Integer.valueOf(cantMatAprobTextField.getText()));
        aluDTO.setFechaIng(new MiCalendario(fecIngDateChooser.getCalendar()));
        aluDTO.setPromedio(Double.valueOf(promTextField.getText()));  
        //.charAt(0) transforma getText del TextField en char
        aluDTO.setEstado(estadoTextField.getText().charAt(0));
        //aluDTO.setEstado('A');
    }

    private void alu2Form(Alumno alu) {
        //setea los textField del dialog tomandolos de los get de la base
        numDocTextField.setText(String.valueOf(alu.getDni()));
        apynTextField.setText(alu.getApyNom());
        fecNacDateChooser.setCalendar(alu.getFechaNac());
    //para cargar el combobox que solo puede ser 0 o 1 usa un if en el get, si es f pone en 0 si no en 1
        sexoComboBox.setSelectedIndex(alu.getSexo()=='f'?0:1);
        cantMatAprobTextField.setText(String.valueOf(alu.getCantMatAprob()));
        fecIngDateChooser.setCalendar(alu.getFechaIng());
        estadoTextField.setText(String.valueOf(alu.getEstado()));
        promTextField.setText(String.valueOf(alu.getPromedio()));
    }

    private void habilitarDeshabilitar(boolean isUpdate) {
        //deshabilita o habilita fecNacDateChooser dependiendo de la acción
        numDocTextField.setEnabled(false);
        apynTextField.setEnabled(isUpdate);
        fecNacDateChooser.setEnabled(isUpdate);
        sexoComboBox.setEnabled(isUpdate);
        cantMatAprobTextField.setEnabled(isUpdate);
        fecIngDateChooser.setEnabled(isUpdate);
        estadoTextField.setEnabled(isUpdate);
        promTextField.setEnabled(isUpdate);
        saveButton.setEnabled(isUpdate);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apynTextField;
    private javax.swing.JTextField cantMatAprobTextField;
    private javax.swing.JTextField estadoTextField;
    private com.toedter.calendar.JDateChooser fecIngDateChooser;
    private com.toedter.calendar.JDateChooser fecNacDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField numDocTextField;
    private javax.swing.JTextField promTextField;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox<String> sexoComboBox;
    // End of variables declaration//GEN-END:variables
}
